name: Build ARMv7-AHF

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-armv7:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ARM cross-compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf make

      - name: Build project for ARMv7-AHF
        run: |
          make clean
          # 使用交叉编译器
          make CC=arm-linux-gnueabihf-gcc CXX=arm-linux-gnueabihf-g++

      - name: Upload ARMv7 binary
        uses: actions/upload-artifact@v3
        with:
          name: armv7-binary
          path: your_executable_name  # 替换为 Makefile 生成的可执行文件名
